// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw5Qbtx3aelPsjRPEdl8OOTGgl268wid8',
    appId: '1:642161392142:web:6b57ea4c4488fe13af9a5f',
    messagingSenderId: '642161392142',
    projectId: 'project-consumer-76309',
    authDomain: 'project-consumer-76309.firebaseapp.com',
    storageBucket: 'project-consumer-76309.appspot.com',
    measurementId: 'G-V2TKSHE4SR',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDncthhpp6Ia5_EW0NcSibQfkkUAK9kZN4',
    appId: '1:642161392142:ios:9dec949af9ab579aaf9a5f',
    messagingSenderId: '642161392142',
    projectId: 'project-consumer-76309',
    storageBucket: 'project-consumer-76309.appspot.com',
    androidClientId: '642161392142-ijtko1kkakdd75sfqpiimrau2e432re4.apps.googleusercontent.com',
    iosClientId: '642161392142-8plt4054ceil5oilet6m2vm6l17b957c.apps.googleusercontent.com',
    iosBundleId: 'com.example.watchlistfyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDncthhpp6Ia5_EW0NcSibQfkkUAK9kZN4',
    appId: '1:642161392142:ios:ceda0dbc4c438d2aaf9a5f',
    messagingSenderId: '642161392142',
    projectId: 'project-consumer-76309',
    storageBucket: 'project-consumer-76309.appspot.com',
    androidClientId: '642161392142-ijtko1kkakdd75sfqpiimrau2e432re4.apps.googleusercontent.com',
    iosClientId: '642161392142-p7dridbhqmusjd0uk2m0nmprol9v2l29.apps.googleusercontent.com',
    iosBundleId: 'com.example.watchlistfyFlutter.RunnerTests',
  );
}
